# Generated by Django 3.2.12 on 2024-07-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hospital_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('experience', models.PositiveIntegerField()),
                ('op_time', models.CharField(max_length=20)),
                ('time_slots', models.JSONField()),
                ('days', models.JSONField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='api.department')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'api_doctor',
                'managed': True,
            },
        ),
    ]
