# Generated by Django 3.2.12 on 2024-07-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='time_slots',
        ),
    ]
