# Generated by Django 3.2.12 on 2024-07-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_doctor_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='days',
        ),
    ]
