# Generated by Django 3.2.12 on 2024-08-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
