# Generated by Django 3.2.12 on 2024-08-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Upcoming'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
