# Generated by Django 3.2.12 on 2024-08-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded'), ('Completed', 'Completed')], default='Upcoming', max_length=10),
        ),
    ]
