# Generated by Django 3.2.12 on 2024-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='appointment_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
