# Generated by Django 3.2.12 on 2024-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
