# Generated by Django 3.2.12 on 2024-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0023_auto_20240820_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='hospital_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='hospital_permissions', to='auth.Permission'),
        ),
    ]
