# Generated by Django 3.2.12 on 2024-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20240820_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('wallet', 'Wallet')], default='razorpay', max_length=10),
        ),
    ]
