# Generated by Django 3.2.12 on 2024-09-05 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_premiumhospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
