# Generated by Django 5.1.1 on 2024-09-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.JSONField(),
        ),
    ]
